### ISSUE TITLE
ArrayIndexOutOfBoundsException in StresstestResultProcessor

### ISSUE THREAD

**Issue by nck-mlcnv** [dice-group/IGUANA#249]
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
        at org.aksw.iguana.cc.tasks.impl.StresstestResultProcessor.process(StresstestResultProcessor.java:92)
        at org.aksw.iguana.cc.tasks.impl.Stresstest.run(Stresstest.java:93)
        at org.aksw.iguana.cc.suite.Suite.run(Suite.java:98)
        at org.aksw.iguana.cc.controller.MainController.main(MainController.java:73)


```

**Comment by bigerl** [comment]
@nck-mlcnv  what was the matter here?

**Comment by nck-mlcnv** [comment]
The StresstestResultProcessor created arrays that stored results for every worker. For the access of these arrays the worker id was used. But if you have used warmup workers before the workerids of the actual run didn't correlate to the indices of the array.

I fixed it by reseting the workerids to 0 after the warmup was done.
