### ISSUE TITLE
Configuration file checking should occur before running any of the tests

### ISSUE THREAD

**Issue by earthquakesan** [dice-group/IGUANA#68]
After warm up phase I received this error message:
```
[SEVERE  Sat Sep 30 13:53:43 CEST 2017] java.lang.NullPointerException
	at org.aksw.iguana.testcases.StressTestcase.getFilesForUpdateWorker(StressTestcase.java:739)
	at org.aksw.iguana.testcases.StressTestcase.setProperties(StressTestcase.java:723)
	at org.aksw.iguana.benchmark.processor.TestcaseProcessor.testTestcase(TestcaseProcessor.java:178)
	at org.aksw.iguana.benchmark.Benchmark.start(Benchmark.java:177)
	at org.aksw.iguana.benchmark.Benchmark.execute(Benchmark.java:64)
	at org.aksw.iguana.benchmark.Main.main(Main.java:57)
```

Basically, I forgot to download and include changesets. All the files should be checked before running the actual tasks.

**Comment by TortugaAttack** [comment]
in the new version the QueryHandler will tell you that you missing files. 
But it will still try to execute the benchmark. 

The validation before the task is not possible, as files can be created during the initialization of the task. 
To decide wether or wether not the given files are generated or not, is not possible. 

I will add a Validator though, so one can check if the configuration is valid and all files are existing.
